# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/simon/dev/gemu

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/simon/dev/gemu

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/simon/dev/gemu/CMakeFiles /home/simon/dev/gemu//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/simon/dev/gemu/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gemu

# Build rule for target.
gemu: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gemu
.PHONY : gemu

# fast build rule for target.
gemu/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/build
.PHONY : gemu/fast

#=============================================================================
# Target rules for targets named SDL3-shared

# Build rule for target.
SDL3-shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL3-shared
.PHONY : SDL3-shared

# fast build rule for target.
SDL3-shared/fast:
	$(MAKE) $(MAKESILENT) -f vendored/SDL/CMakeFiles/SDL3-shared.dir/build.make vendored/SDL/CMakeFiles/SDL3-shared.dir/build
.PHONY : SDL3-shared/fast

#=============================================================================
# Target rules for targets named SDL3_test

# Build rule for target.
SDL3_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL3_test
.PHONY : SDL3_test

# fast build rule for target.
SDL3_test/fast:
	$(MAKE) $(MAKESILENT) -f vendored/SDL/CMakeFiles/SDL3_test.dir/build.make vendored/SDL/CMakeFiles/SDL3_test.dir/build
.PHONY : SDL3_test/fast

#=============================================================================
# Target rules for targets named SDL_uclibc

# Build rule for target.
SDL_uclibc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SDL_uclibc
.PHONY : SDL_uclibc

# fast build rule for target.
SDL_uclibc/fast:
	$(MAKE) $(MAKESILENT) -f vendored/SDL/CMakeFiles/SDL_uclibc.dir/build.make vendored/SDL/CMakeFiles/SDL_uclibc.dir/build
.PHONY : SDL_uclibc/fast

cpu/Audio.o: cpu/Audio.cpp.o
.PHONY : cpu/Audio.o

# target to build an object file
cpu/Audio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/Audio.cpp.o
.PHONY : cpu/Audio.cpp.o

cpu/Audio.i: cpu/Audio.cpp.i
.PHONY : cpu/Audio.i

# target to preprocess a source file
cpu/Audio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/Audio.cpp.i
.PHONY : cpu/Audio.cpp.i

cpu/Audio.s: cpu/Audio.cpp.s
.PHONY : cpu/Audio.s

# target to generate assembly for a file
cpu/Audio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/Audio.cpp.s
.PHONY : cpu/Audio.cpp.s

cpu/CPU.o: cpu/CPU.cpp.o
.PHONY : cpu/CPU.o

# target to build an object file
cpu/CPU.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/CPU.cpp.o
.PHONY : cpu/CPU.cpp.o

cpu/CPU.i: cpu/CPU.cpp.i
.PHONY : cpu/CPU.i

# target to preprocess a source file
cpu/CPU.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/CPU.cpp.i
.PHONY : cpu/CPU.cpp.i

cpu/CPU.s: cpu/CPU.cpp.s
.PHONY : cpu/CPU.s

# target to generate assembly for a file
cpu/CPU.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/CPU.cpp.s
.PHONY : cpu/CPU.cpp.s

cpu/Disassembler.o: cpu/Disassembler.cpp.o
.PHONY : cpu/Disassembler.o

# target to build an object file
cpu/Disassembler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/Disassembler.cpp.o
.PHONY : cpu/Disassembler.cpp.o

cpu/Disassembler.i: cpu/Disassembler.cpp.i
.PHONY : cpu/Disassembler.i

# target to preprocess a source file
cpu/Disassembler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/Disassembler.cpp.i
.PHONY : cpu/Disassembler.cpp.i

cpu/Disassembler.s: cpu/Disassembler.cpp.s
.PHONY : cpu/Disassembler.s

# target to generate assembly for a file
cpu/Disassembler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/Disassembler.cpp.s
.PHONY : cpu/Disassembler.cpp.s

cpu/Graphics.o: cpu/Graphics.cpp.o
.PHONY : cpu/Graphics.o

# target to build an object file
cpu/Graphics.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/Graphics.cpp.o
.PHONY : cpu/Graphics.cpp.o

cpu/Graphics.i: cpu/Graphics.cpp.i
.PHONY : cpu/Graphics.i

# target to preprocess a source file
cpu/Graphics.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/Graphics.cpp.i
.PHONY : cpu/Graphics.cpp.i

cpu/Graphics.s: cpu/Graphics.cpp.s
.PHONY : cpu/Graphics.s

# target to generate assembly for a file
cpu/Graphics.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/Graphics.cpp.s
.PHONY : cpu/Graphics.cpp.s

cpu/Instruction.o: cpu/Instruction.cpp.o
.PHONY : cpu/Instruction.o

# target to build an object file
cpu/Instruction.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/Instruction.cpp.o
.PHONY : cpu/Instruction.cpp.o

cpu/Instruction.i: cpu/Instruction.cpp.i
.PHONY : cpu/Instruction.i

# target to preprocess a source file
cpu/Instruction.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/Instruction.cpp.i
.PHONY : cpu/Instruction.cpp.i

cpu/Instruction.s: cpu/Instruction.cpp.s
.PHONY : cpu/Instruction.s

# target to generate assembly for a file
cpu/Instruction.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/Instruction.cpp.s
.PHONY : cpu/Instruction.cpp.s

cpu/Interrupts.o: cpu/Interrupts.cpp.o
.PHONY : cpu/Interrupts.o

# target to build an object file
cpu/Interrupts.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/Interrupts.cpp.o
.PHONY : cpu/Interrupts.cpp.o

cpu/Interrupts.i: cpu/Interrupts.cpp.i
.PHONY : cpu/Interrupts.i

# target to preprocess a source file
cpu/Interrupts.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/Interrupts.cpp.i
.PHONY : cpu/Interrupts.cpp.i

cpu/Interrupts.s: cpu/Interrupts.cpp.s
.PHONY : cpu/Interrupts.s

# target to generate assembly for a file
cpu/Interrupts.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/Interrupts.cpp.s
.PHONY : cpu/Interrupts.cpp.s

cpu/Timer.o: cpu/Timer.cpp.o
.PHONY : cpu/Timer.o

# target to build an object file
cpu/Timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/Timer.cpp.o
.PHONY : cpu/Timer.cpp.o

cpu/Timer.i: cpu/Timer.cpp.i
.PHONY : cpu/Timer.i

# target to preprocess a source file
cpu/Timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/Timer.cpp.i
.PHONY : cpu/Timer.cpp.i

cpu/Timer.s: cpu/Timer.cpp.s
.PHONY : cpu/Timer.s

# target to generate assembly for a file
cpu/Timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/Timer.cpp.s
.PHONY : cpu/Timer.cpp.s

cpu/instructions/ADC.o: cpu/instructions/ADC.cpp.o
.PHONY : cpu/instructions/ADC.o

# target to build an object file
cpu/instructions/ADC.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/ADC.cpp.o
.PHONY : cpu/instructions/ADC.cpp.o

cpu/instructions/ADC.i: cpu/instructions/ADC.cpp.i
.PHONY : cpu/instructions/ADC.i

# target to preprocess a source file
cpu/instructions/ADC.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/ADC.cpp.i
.PHONY : cpu/instructions/ADC.cpp.i

cpu/instructions/ADC.s: cpu/instructions/ADC.cpp.s
.PHONY : cpu/instructions/ADC.s

# target to generate assembly for a file
cpu/instructions/ADC.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/ADC.cpp.s
.PHONY : cpu/instructions/ADC.cpp.s

cpu/instructions/ADD.o: cpu/instructions/ADD.cpp.o
.PHONY : cpu/instructions/ADD.o

# target to build an object file
cpu/instructions/ADD.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/ADD.cpp.o
.PHONY : cpu/instructions/ADD.cpp.o

cpu/instructions/ADD.i: cpu/instructions/ADD.cpp.i
.PHONY : cpu/instructions/ADD.i

# target to preprocess a source file
cpu/instructions/ADD.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/ADD.cpp.i
.PHONY : cpu/instructions/ADD.cpp.i

cpu/instructions/ADD.s: cpu/instructions/ADD.cpp.s
.PHONY : cpu/instructions/ADD.s

# target to generate assembly for a file
cpu/instructions/ADD.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/ADD.cpp.s
.PHONY : cpu/instructions/ADD.cpp.s

cpu/instructions/AND.o: cpu/instructions/AND.cpp.o
.PHONY : cpu/instructions/AND.o

# target to build an object file
cpu/instructions/AND.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/AND.cpp.o
.PHONY : cpu/instructions/AND.cpp.o

cpu/instructions/AND.i: cpu/instructions/AND.cpp.i
.PHONY : cpu/instructions/AND.i

# target to preprocess a source file
cpu/instructions/AND.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/AND.cpp.i
.PHONY : cpu/instructions/AND.cpp.i

cpu/instructions/AND.s: cpu/instructions/AND.cpp.s
.PHONY : cpu/instructions/AND.s

# target to generate assembly for a file
cpu/instructions/AND.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/AND.cpp.s
.PHONY : cpu/instructions/AND.cpp.s

cpu/instructions/CALL.o: cpu/instructions/CALL.cpp.o
.PHONY : cpu/instructions/CALL.o

# target to build an object file
cpu/instructions/CALL.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/CALL.cpp.o
.PHONY : cpu/instructions/CALL.cpp.o

cpu/instructions/CALL.i: cpu/instructions/CALL.cpp.i
.PHONY : cpu/instructions/CALL.i

# target to preprocess a source file
cpu/instructions/CALL.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/CALL.cpp.i
.PHONY : cpu/instructions/CALL.cpp.i

cpu/instructions/CALL.s: cpu/instructions/CALL.cpp.s
.PHONY : cpu/instructions/CALL.s

# target to generate assembly for a file
cpu/instructions/CALL.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/CALL.cpp.s
.PHONY : cpu/instructions/CALL.cpp.s

cpu/instructions/CP.o: cpu/instructions/CP.cpp.o
.PHONY : cpu/instructions/CP.o

# target to build an object file
cpu/instructions/CP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/CP.cpp.o
.PHONY : cpu/instructions/CP.cpp.o

cpu/instructions/CP.i: cpu/instructions/CP.cpp.i
.PHONY : cpu/instructions/CP.i

# target to preprocess a source file
cpu/instructions/CP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/CP.cpp.i
.PHONY : cpu/instructions/CP.cpp.i

cpu/instructions/CP.s: cpu/instructions/CP.cpp.s
.PHONY : cpu/instructions/CP.s

# target to generate assembly for a file
cpu/instructions/CP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/CP.cpp.s
.PHONY : cpu/instructions/CP.cpp.s

cpu/instructions/DEC.o: cpu/instructions/DEC.cpp.o
.PHONY : cpu/instructions/DEC.o

# target to build an object file
cpu/instructions/DEC.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/DEC.cpp.o
.PHONY : cpu/instructions/DEC.cpp.o

cpu/instructions/DEC.i: cpu/instructions/DEC.cpp.i
.PHONY : cpu/instructions/DEC.i

# target to preprocess a source file
cpu/instructions/DEC.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/DEC.cpp.i
.PHONY : cpu/instructions/DEC.cpp.i

cpu/instructions/DEC.s: cpu/instructions/DEC.cpp.s
.PHONY : cpu/instructions/DEC.s

# target to generate assembly for a file
cpu/instructions/DEC.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/DEC.cpp.s
.PHONY : cpu/instructions/DEC.cpp.s

cpu/instructions/DI.o: cpu/instructions/DI.cpp.o
.PHONY : cpu/instructions/DI.o

# target to build an object file
cpu/instructions/DI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/DI.cpp.o
.PHONY : cpu/instructions/DI.cpp.o

cpu/instructions/DI.i: cpu/instructions/DI.cpp.i
.PHONY : cpu/instructions/DI.i

# target to preprocess a source file
cpu/instructions/DI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/DI.cpp.i
.PHONY : cpu/instructions/DI.cpp.i

cpu/instructions/DI.s: cpu/instructions/DI.cpp.s
.PHONY : cpu/instructions/DI.s

# target to generate assembly for a file
cpu/instructions/DI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/DI.cpp.s
.PHONY : cpu/instructions/DI.cpp.s

cpu/instructions/INC.o: cpu/instructions/INC.cpp.o
.PHONY : cpu/instructions/INC.o

# target to build an object file
cpu/instructions/INC.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/INC.cpp.o
.PHONY : cpu/instructions/INC.cpp.o

cpu/instructions/INC.i: cpu/instructions/INC.cpp.i
.PHONY : cpu/instructions/INC.i

# target to preprocess a source file
cpu/instructions/INC.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/INC.cpp.i
.PHONY : cpu/instructions/INC.cpp.i

cpu/instructions/INC.s: cpu/instructions/INC.cpp.s
.PHONY : cpu/instructions/INC.s

# target to generate assembly for a file
cpu/instructions/INC.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/INC.cpp.s
.PHONY : cpu/instructions/INC.cpp.s

cpu/instructions/JP.o: cpu/instructions/JP.cpp.o
.PHONY : cpu/instructions/JP.o

# target to build an object file
cpu/instructions/JP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/JP.cpp.o
.PHONY : cpu/instructions/JP.cpp.o

cpu/instructions/JP.i: cpu/instructions/JP.cpp.i
.PHONY : cpu/instructions/JP.i

# target to preprocess a source file
cpu/instructions/JP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/JP.cpp.i
.PHONY : cpu/instructions/JP.cpp.i

cpu/instructions/JP.s: cpu/instructions/JP.cpp.s
.PHONY : cpu/instructions/JP.s

# target to generate assembly for a file
cpu/instructions/JP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/JP.cpp.s
.PHONY : cpu/instructions/JP.cpp.s

cpu/instructions/JR.o: cpu/instructions/JR.cpp.o
.PHONY : cpu/instructions/JR.o

# target to build an object file
cpu/instructions/JR.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/JR.cpp.o
.PHONY : cpu/instructions/JR.cpp.o

cpu/instructions/JR.i: cpu/instructions/JR.cpp.i
.PHONY : cpu/instructions/JR.i

# target to preprocess a source file
cpu/instructions/JR.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/JR.cpp.i
.PHONY : cpu/instructions/JR.cpp.i

cpu/instructions/JR.s: cpu/instructions/JR.cpp.s
.PHONY : cpu/instructions/JR.s

# target to generate assembly for a file
cpu/instructions/JR.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/JR.cpp.s
.PHONY : cpu/instructions/JR.cpp.s

cpu/instructions/LD.o: cpu/instructions/LD.cpp.o
.PHONY : cpu/instructions/LD.o

# target to build an object file
cpu/instructions/LD.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/LD.cpp.o
.PHONY : cpu/instructions/LD.cpp.o

cpu/instructions/LD.i: cpu/instructions/LD.cpp.i
.PHONY : cpu/instructions/LD.i

# target to preprocess a source file
cpu/instructions/LD.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/LD.cpp.i
.PHONY : cpu/instructions/LD.cpp.i

cpu/instructions/LD.s: cpu/instructions/LD.cpp.s
.PHONY : cpu/instructions/LD.s

# target to generate assembly for a file
cpu/instructions/LD.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/LD.cpp.s
.PHONY : cpu/instructions/LD.cpp.s

cpu/instructions/LDH.o: cpu/instructions/LDH.cpp.o
.PHONY : cpu/instructions/LDH.o

# target to build an object file
cpu/instructions/LDH.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/LDH.cpp.o
.PHONY : cpu/instructions/LDH.cpp.o

cpu/instructions/LDH.i: cpu/instructions/LDH.cpp.i
.PHONY : cpu/instructions/LDH.i

# target to preprocess a source file
cpu/instructions/LDH.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/LDH.cpp.i
.PHONY : cpu/instructions/LDH.cpp.i

cpu/instructions/LDH.s: cpu/instructions/LDH.cpp.s
.PHONY : cpu/instructions/LDH.s

# target to generate assembly for a file
cpu/instructions/LDH.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/LDH.cpp.s
.PHONY : cpu/instructions/LDH.cpp.s

cpu/instructions/NOP.o: cpu/instructions/NOP.cpp.o
.PHONY : cpu/instructions/NOP.o

# target to build an object file
cpu/instructions/NOP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/NOP.cpp.o
.PHONY : cpu/instructions/NOP.cpp.o

cpu/instructions/NOP.i: cpu/instructions/NOP.cpp.i
.PHONY : cpu/instructions/NOP.i

# target to preprocess a source file
cpu/instructions/NOP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/NOP.cpp.i
.PHONY : cpu/instructions/NOP.cpp.i

cpu/instructions/NOP.s: cpu/instructions/NOP.cpp.s
.PHONY : cpu/instructions/NOP.s

# target to generate assembly for a file
cpu/instructions/NOP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/NOP.cpp.s
.PHONY : cpu/instructions/NOP.cpp.s

cpu/instructions/OR.o: cpu/instructions/OR.cpp.o
.PHONY : cpu/instructions/OR.o

# target to build an object file
cpu/instructions/OR.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/OR.cpp.o
.PHONY : cpu/instructions/OR.cpp.o

cpu/instructions/OR.i: cpu/instructions/OR.cpp.i
.PHONY : cpu/instructions/OR.i

# target to preprocess a source file
cpu/instructions/OR.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/OR.cpp.i
.PHONY : cpu/instructions/OR.cpp.i

cpu/instructions/OR.s: cpu/instructions/OR.cpp.s
.PHONY : cpu/instructions/OR.s

# target to generate assembly for a file
cpu/instructions/OR.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/OR.cpp.s
.PHONY : cpu/instructions/OR.cpp.s

cpu/instructions/POP.o: cpu/instructions/POP.cpp.o
.PHONY : cpu/instructions/POP.o

# target to build an object file
cpu/instructions/POP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/POP.cpp.o
.PHONY : cpu/instructions/POP.cpp.o

cpu/instructions/POP.i: cpu/instructions/POP.cpp.i
.PHONY : cpu/instructions/POP.i

# target to preprocess a source file
cpu/instructions/POP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/POP.cpp.i
.PHONY : cpu/instructions/POP.cpp.i

cpu/instructions/POP.s: cpu/instructions/POP.cpp.s
.PHONY : cpu/instructions/POP.s

# target to generate assembly for a file
cpu/instructions/POP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/POP.cpp.s
.PHONY : cpu/instructions/POP.cpp.s

cpu/instructions/PUSH.o: cpu/instructions/PUSH.cpp.o
.PHONY : cpu/instructions/PUSH.o

# target to build an object file
cpu/instructions/PUSH.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/PUSH.cpp.o
.PHONY : cpu/instructions/PUSH.cpp.o

cpu/instructions/PUSH.i: cpu/instructions/PUSH.cpp.i
.PHONY : cpu/instructions/PUSH.i

# target to preprocess a source file
cpu/instructions/PUSH.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/PUSH.cpp.i
.PHONY : cpu/instructions/PUSH.cpp.i

cpu/instructions/PUSH.s: cpu/instructions/PUSH.cpp.s
.PHONY : cpu/instructions/PUSH.s

# target to generate assembly for a file
cpu/instructions/PUSH.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/PUSH.cpp.s
.PHONY : cpu/instructions/PUSH.cpp.s

cpu/instructions/RET.o: cpu/instructions/RET.cpp.o
.PHONY : cpu/instructions/RET.o

# target to build an object file
cpu/instructions/RET.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/RET.cpp.o
.PHONY : cpu/instructions/RET.cpp.o

cpu/instructions/RET.i: cpu/instructions/RET.cpp.i
.PHONY : cpu/instructions/RET.i

# target to preprocess a source file
cpu/instructions/RET.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/RET.cpp.i
.PHONY : cpu/instructions/RET.cpp.i

cpu/instructions/RET.s: cpu/instructions/RET.cpp.s
.PHONY : cpu/instructions/RET.s

# target to generate assembly for a file
cpu/instructions/RET.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/RET.cpp.s
.PHONY : cpu/instructions/RET.cpp.s

cpu/instructions/RLCA.o: cpu/instructions/RLCA.cpp.o
.PHONY : cpu/instructions/RLCA.o

# target to build an object file
cpu/instructions/RLCA.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/RLCA.cpp.o
.PHONY : cpu/instructions/RLCA.cpp.o

cpu/instructions/RLCA.i: cpu/instructions/RLCA.cpp.i
.PHONY : cpu/instructions/RLCA.i

# target to preprocess a source file
cpu/instructions/RLCA.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/RLCA.cpp.i
.PHONY : cpu/instructions/RLCA.cpp.i

cpu/instructions/RLCA.s: cpu/instructions/RLCA.cpp.s
.PHONY : cpu/instructions/RLCA.s

# target to generate assembly for a file
cpu/instructions/RLCA.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/RLCA.cpp.s
.PHONY : cpu/instructions/RLCA.cpp.s

cpu/instructions/RR.o: cpu/instructions/RR.cpp.o
.PHONY : cpu/instructions/RR.o

# target to build an object file
cpu/instructions/RR.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/RR.cpp.o
.PHONY : cpu/instructions/RR.cpp.o

cpu/instructions/RR.i: cpu/instructions/RR.cpp.i
.PHONY : cpu/instructions/RR.i

# target to preprocess a source file
cpu/instructions/RR.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/RR.cpp.i
.PHONY : cpu/instructions/RR.cpp.i

cpu/instructions/RR.s: cpu/instructions/RR.cpp.s
.PHONY : cpu/instructions/RR.s

# target to generate assembly for a file
cpu/instructions/RR.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/RR.cpp.s
.PHONY : cpu/instructions/RR.cpp.s

cpu/instructions/RRA.o: cpu/instructions/RRA.cpp.o
.PHONY : cpu/instructions/RRA.o

# target to build an object file
cpu/instructions/RRA.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/RRA.cpp.o
.PHONY : cpu/instructions/RRA.cpp.o

cpu/instructions/RRA.i: cpu/instructions/RRA.cpp.i
.PHONY : cpu/instructions/RRA.i

# target to preprocess a source file
cpu/instructions/RRA.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/RRA.cpp.i
.PHONY : cpu/instructions/RRA.cpp.i

cpu/instructions/RRA.s: cpu/instructions/RRA.cpp.s
.PHONY : cpu/instructions/RRA.s

# target to generate assembly for a file
cpu/instructions/RRA.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/RRA.cpp.s
.PHONY : cpu/instructions/RRA.cpp.s

cpu/instructions/SRL.o: cpu/instructions/SRL.cpp.o
.PHONY : cpu/instructions/SRL.o

# target to build an object file
cpu/instructions/SRL.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/SRL.cpp.o
.PHONY : cpu/instructions/SRL.cpp.o

cpu/instructions/SRL.i: cpu/instructions/SRL.cpp.i
.PHONY : cpu/instructions/SRL.i

# target to preprocess a source file
cpu/instructions/SRL.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/SRL.cpp.i
.PHONY : cpu/instructions/SRL.cpp.i

cpu/instructions/SRL.s: cpu/instructions/SRL.cpp.s
.PHONY : cpu/instructions/SRL.s

# target to generate assembly for a file
cpu/instructions/SRL.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/SRL.cpp.s
.PHONY : cpu/instructions/SRL.cpp.s

cpu/instructions/STOP.o: cpu/instructions/STOP.cpp.o
.PHONY : cpu/instructions/STOP.o

# target to build an object file
cpu/instructions/STOP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/STOP.cpp.o
.PHONY : cpu/instructions/STOP.cpp.o

cpu/instructions/STOP.i: cpu/instructions/STOP.cpp.i
.PHONY : cpu/instructions/STOP.i

# target to preprocess a source file
cpu/instructions/STOP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/STOP.cpp.i
.PHONY : cpu/instructions/STOP.cpp.i

cpu/instructions/STOP.s: cpu/instructions/STOP.cpp.s
.PHONY : cpu/instructions/STOP.s

# target to generate assembly for a file
cpu/instructions/STOP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/STOP.cpp.s
.PHONY : cpu/instructions/STOP.cpp.s

cpu/instructions/SUB.o: cpu/instructions/SUB.cpp.o
.PHONY : cpu/instructions/SUB.o

# target to build an object file
cpu/instructions/SUB.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/SUB.cpp.o
.PHONY : cpu/instructions/SUB.cpp.o

cpu/instructions/SUB.i: cpu/instructions/SUB.cpp.i
.PHONY : cpu/instructions/SUB.i

# target to preprocess a source file
cpu/instructions/SUB.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/SUB.cpp.i
.PHONY : cpu/instructions/SUB.cpp.i

cpu/instructions/SUB.s: cpu/instructions/SUB.cpp.s
.PHONY : cpu/instructions/SUB.s

# target to generate assembly for a file
cpu/instructions/SUB.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/SUB.cpp.s
.PHONY : cpu/instructions/SUB.cpp.s

cpu/instructions/XOR.o: cpu/instructions/XOR.cpp.o
.PHONY : cpu/instructions/XOR.o

# target to build an object file
cpu/instructions/XOR.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/XOR.cpp.o
.PHONY : cpu/instructions/XOR.cpp.o

cpu/instructions/XOR.i: cpu/instructions/XOR.cpp.i
.PHONY : cpu/instructions/XOR.i

# target to preprocess a source file
cpu/instructions/XOR.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/XOR.cpp.i
.PHONY : cpu/instructions/XOR.cpp.i

cpu/instructions/XOR.s: cpu/instructions/XOR.cpp.s
.PHONY : cpu/instructions/XOR.s

# target to generate assembly for a file
cpu/instructions/XOR.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/cpu/instructions/XOR.cpp.s
.PHONY : cpu/instructions/XOR.cpp.s

display/Window.o: display/Window.cpp.o
.PHONY : display/Window.o

# target to build an object file
display/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/display/Window.cpp.o
.PHONY : display/Window.cpp.o

display/Window.i: display/Window.cpp.i
.PHONY : display/Window.i

# target to preprocess a source file
display/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/display/Window.cpp.i
.PHONY : display/Window.cpp.i

display/Window.s: display/Window.cpp.s
.PHONY : display/Window.s

# target to generate assembly for a file
display/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gemu.dir/build.make CMakeFiles/gemu.dir/display/Window.cpp.s
.PHONY : display/Window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SDL3-shared"
	@echo "... SDL3_test"
	@echo "... SDL_uclibc"
	@echo "... gemu"
	@echo "... cpu/Audio.o"
	@echo "... cpu/Audio.i"
	@echo "... cpu/Audio.s"
	@echo "... cpu/CPU.o"
	@echo "... cpu/CPU.i"
	@echo "... cpu/CPU.s"
	@echo "... cpu/Disassembler.o"
	@echo "... cpu/Disassembler.i"
	@echo "... cpu/Disassembler.s"
	@echo "... cpu/Graphics.o"
	@echo "... cpu/Graphics.i"
	@echo "... cpu/Graphics.s"
	@echo "... cpu/Instruction.o"
	@echo "... cpu/Instruction.i"
	@echo "... cpu/Instruction.s"
	@echo "... cpu/Interrupts.o"
	@echo "... cpu/Interrupts.i"
	@echo "... cpu/Interrupts.s"
	@echo "... cpu/Timer.o"
	@echo "... cpu/Timer.i"
	@echo "... cpu/Timer.s"
	@echo "... cpu/instructions/ADC.o"
	@echo "... cpu/instructions/ADC.i"
	@echo "... cpu/instructions/ADC.s"
	@echo "... cpu/instructions/ADD.o"
	@echo "... cpu/instructions/ADD.i"
	@echo "... cpu/instructions/ADD.s"
	@echo "... cpu/instructions/AND.o"
	@echo "... cpu/instructions/AND.i"
	@echo "... cpu/instructions/AND.s"
	@echo "... cpu/instructions/CALL.o"
	@echo "... cpu/instructions/CALL.i"
	@echo "... cpu/instructions/CALL.s"
	@echo "... cpu/instructions/CP.o"
	@echo "... cpu/instructions/CP.i"
	@echo "... cpu/instructions/CP.s"
	@echo "... cpu/instructions/DEC.o"
	@echo "... cpu/instructions/DEC.i"
	@echo "... cpu/instructions/DEC.s"
	@echo "... cpu/instructions/DI.o"
	@echo "... cpu/instructions/DI.i"
	@echo "... cpu/instructions/DI.s"
	@echo "... cpu/instructions/INC.o"
	@echo "... cpu/instructions/INC.i"
	@echo "... cpu/instructions/INC.s"
	@echo "... cpu/instructions/JP.o"
	@echo "... cpu/instructions/JP.i"
	@echo "... cpu/instructions/JP.s"
	@echo "... cpu/instructions/JR.o"
	@echo "... cpu/instructions/JR.i"
	@echo "... cpu/instructions/JR.s"
	@echo "... cpu/instructions/LD.o"
	@echo "... cpu/instructions/LD.i"
	@echo "... cpu/instructions/LD.s"
	@echo "... cpu/instructions/LDH.o"
	@echo "... cpu/instructions/LDH.i"
	@echo "... cpu/instructions/LDH.s"
	@echo "... cpu/instructions/NOP.o"
	@echo "... cpu/instructions/NOP.i"
	@echo "... cpu/instructions/NOP.s"
	@echo "... cpu/instructions/OR.o"
	@echo "... cpu/instructions/OR.i"
	@echo "... cpu/instructions/OR.s"
	@echo "... cpu/instructions/POP.o"
	@echo "... cpu/instructions/POP.i"
	@echo "... cpu/instructions/POP.s"
	@echo "... cpu/instructions/PUSH.o"
	@echo "... cpu/instructions/PUSH.i"
	@echo "... cpu/instructions/PUSH.s"
	@echo "... cpu/instructions/RET.o"
	@echo "... cpu/instructions/RET.i"
	@echo "... cpu/instructions/RET.s"
	@echo "... cpu/instructions/RLCA.o"
	@echo "... cpu/instructions/RLCA.i"
	@echo "... cpu/instructions/RLCA.s"
	@echo "... cpu/instructions/RR.o"
	@echo "... cpu/instructions/RR.i"
	@echo "... cpu/instructions/RR.s"
	@echo "... cpu/instructions/RRA.o"
	@echo "... cpu/instructions/RRA.i"
	@echo "... cpu/instructions/RRA.s"
	@echo "... cpu/instructions/SRL.o"
	@echo "... cpu/instructions/SRL.i"
	@echo "... cpu/instructions/SRL.s"
	@echo "... cpu/instructions/STOP.o"
	@echo "... cpu/instructions/STOP.i"
	@echo "... cpu/instructions/STOP.s"
	@echo "... cpu/instructions/SUB.o"
	@echo "... cpu/instructions/SUB.i"
	@echo "... cpu/instructions/SUB.s"
	@echo "... cpu/instructions/XOR.o"
	@echo "... cpu/instructions/XOR.i"
	@echo "... cpu/instructions/XOR.s"
	@echo "... display/Window.o"
	@echo "... display/Window.i"
	@echo "... display/Window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

